name: Backend workflow
run-name: End-to-end and unit tests for schema validation BE
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Excecute end-to-end tests
        run: npm run test