name: Tests
run-name: End-to-end and unit tests
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2       # checkout the repo
      - name: Install modules
        run: npm ci                     # install packages (`yarn` is alternative here)
      - name: Run end-to-end tests
        run: npm test